### PR TITLE
Created a Basic UI

### PR DESCRIPTION
**Pull request by hrishikeshsoman**
@nishintn @aswathym 
Hi,
 
Please find the pull request for the branch 'BasicUI' which includes the very basic UI for the Reminder app.

Thanks.

### CODE REVIEW

**Comment by nishintn** [comment]
@hrishikeshsoman ,
Can you share the local link?

**Comment by hrishikeshsoman** [comment]
@nishintn 
The local link is : 10.9.12.123/ReminderApp/

**Comment by nishintn** [comment]
@hrishikeshsoman 
Move the search from menu to the right side of the header.

**Comment by hrishikeshsoman** [comment]
@nishintn 
Hi,

The position of search bar changed to right side of header. Please find it here : http://10.9.12.123/ReminderApp/

Thanks.

**Pull request merged**
